name: Java CI

on:
  push:
    paths-ignore: 
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # See: https://adoptium.net/temurin/releases/
        java: [ 8, 11, 17, 21 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build with Gradle
        run: ./gradlew build
